#!/usr/bin/env bash

# welcome msg
echo "Hello~~~~~~ Fighto!!! (> <)/"
#Locale
export LC_ALL="zh_TW.UTF-8"
export LANG="zh_TW"

# composer
export PATH=$PATH:"/Applications/MAMP/bin/php/php7.0.0/bin":"/Users/dotdev/bin":"$HOME/.composer/vendor/bin"

#gnupg settings
export GNUPGHOME="/home/blahblah/.gnupg"

#Monpig's specific aliases and functions
alias clr='clear'
alias rmd='rm -rf'
alias grep="grep --color=auto"
alias vi='vim'
alias mysql='/Applications/MAMP/Library/bin/mysql'
#alias php='/Applications/MAMP/bin/php/php7.0.0/bin/php'
#alias phpize='/Applications/MAMP/bin/php/php7.0.0/bin/phpize'

#Colorized ls
DIR=Dx
SYM_LINK=Gx
SOCKET=Fx
PIPE=dx
EXE=Cx
BLOCK_SP=Dx
CHAR_SP=Dx
EXE_SUID=hb
EXE_GUID=ad
DIR_STICKY=Ex
DIR_WO_STICKY=Ex
export LSCOLORS="$DIR$SYM_LINK$SOCKET$PIPE$EXE$BLOCK_SP$CHAR_SP$EXE_SUID$EXE_GUID$DIR_STICKY$DIR_WO_STICKY"

alias ls="ls -Gal"
alias lsm="\ls | more"


#alias for TMUX

export EDITOR="vim"

#Check if TMUX already exist
# test -z "$TMUX" && (tmux attach || tmux new -s Monpig)

#Git

function git_branch {
    ref=$(git symbolic-ref HEAD 2> /dev/null) || return;
    echo "("${ref#refs/heads/}") ";
}
 
function git_since_last_commit {
    now=`date +%s`;
    last_commit=$(git log --pretty=format:%at -1 2> /dev/null) || return;
    seconds_since_last_commit=$((now-last_commit));
    minutes_since_last_commit=$((seconds_since_last_commit/60));
    hours_since_last_commit=$((minutes_since_last_commit/60));
    minutes_since_last_commit=$((minutes_since_last_commit%60));
    
    echo "${hours_since_last_commit}h${minutes_since_last_commit}m ";
}
 
PS1="[\[\033[1;32m\]\w\[\033[0m\]] \[\033[0m\]\[\033[1;36m\]\$(git_branch)\[\033[0;33m\]\$(git_since_last_commit)\[\033[0m\]$ "

export NVM_DIR="/Users/dotdev/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi
