#!/usr/bin/env bash

DIFF=`which diff`
CWD=`pwd`     
file_ls=`ls -d _*`

echo "Change to $CWD";

function link {
    srcfile="${CWD}/${1}"
    destfile="$HOME/${1/_/.}"
	echo "${destfile}"
    if [ -f $destfile ]; then
	    if [ -n "$($DIFF $srcfile $destfile)" ]; then
            backup $destfile
		fi
	fi
        ln -s $srcfile $destfile
}

function backup {
    if [ -r $1 ]; then
        backupfile="$1.bak"
        if [ -r $backupfile ]; then
            rm $backupfile
        fi
        mv $1 $backupfile 
        echo "Backup $1 to $backupfile"   
    else
        echo "File $1 doesn't exist."
    fi 
}

for file in $file_ls; do
    link $file
done
